# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ael-idri <ael-idri@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/05 11:34:00 by ael-idri          #+#    #+#              #
#    Updated: 2022/11/05 11:51:41 by ael-idri         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
       
version: '3'

services:

  mariadb:
    build: 
        context: ./srcs/requirements/mariadb/
        args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - chabaka
    volumes:
      - data:/var/lib/mysql
    restart: always

  redis:
    build: ./srcs/requirements/bonus/redis/
    image: redis
    container_name: redis
    networks:
      - chabaka
    restart: always

  adminer:
    build: ./srcs/requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - chabaka
    restart: always

  ftp:
    build: ./srcs/requirements/bonus/ftp/
    image: ftp
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    environment:
      - FTP_USER=hliwa
      - FTP_PASS=secret
      - PASV_ADDRESS=localhost
    networks:
      - chabaka
    restart: always

  website:
    build: ./srcs/requirements/bonus/website/
    image: website
    container_name: website
    ports:
      - "80:80"
    networks:
      - chabaka
    restart: always

  cadvisor:
    build: ./srcs/requirements/bonus/cadvisor/
    image: cadvisor
    container_name: cadvisor
    ports:
      - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - chabaka
    restart: always

  wordpress:
    build:
      context: ./srcs/requirements/wordpress/
      args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
          ADMIN_USER: $ADMIN_USER
          ADMIN_PASSWORD: $ADMIN_PASSWORD
    image : wordpress
    env_file: .env
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wpress:/var/www/html/
    networks:
      - chabaka
    restart: always

  nginx:
    build:
      context: ./srcs/requirements/nginx/
      args:
        _CERTIF: $_CERTIF
        _CERTIF_key: $_CERTIF_key
        _CERTIF_crt : $_CERTIF_crt
    image: nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wpress:/var/www/html/
    networks:
      - chabaka
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always



networks:
  chabaka:
    driver: bridge
  
volumes:
  data:
    driver_opts:
      type: none
      o: bind
      device: /Users/ael-idri/Desktop/inception/data/db
  wpress:
    driver_opts:
      type: none
      o: bind
      device: /Users/ael-idri/Desktop/inception/data/wp

