    
version: '3'

services:

  nginx:
    build:
      context: ./requirements/nginx/
      args:
        _CERTIF: $_CERTIF
        _CERTIF_key: $_CERTIF_key
        _CERTIF_crt : $_CERTIF_crt
    image: nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wpress:/var/www/html/
    networks:
      - chabaka
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress/
      args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
          ADMIN_USER: $ADMIN_USER
          ADMIN_PASSWORD: $ADMIN_PASSWORD
    image : wordpress
    env_file: .env
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wpress:/var/www/html/
    networks:
      - chabaka
    restart: always

  mariadb:
    build:
        context: ./requirements/mariadb/
        args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - chabaka
    volumes:
      - data:/var/lib/mysql
    restart: always

  redis:
    build: ./requirements/bonus/redis/
    image: redis
    container_name: redis
    networks:
      - chabaka
    restart: always

  adminer:
    build: ./requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - chabaka
    restart: always

  ftp:
    build: ./requirements/bonus/ftp/
    image: ftp
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    environment:
      - FTP_USER=hliwa
      - FTP_PASS=secret
      - PASV_ADDRESS=localhost
    depends_on:
      - wordpress
    volumes:
      - wpress:/home/hliwa
    networks:
      - chabaka
    restart: always

  website:
    build: ./requirements/bonus/website/
    image: website
    container_name: website
    ports:
      - "80:80"
    networks:
      - chabaka
    restart: always

  cadvisor:
    build: ./requirements/bonus/cadvisor/
    image: cadvisor
    container_name: cadvisor
    ports:
      - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - chabaka
    restart: always


networks:
  chabaka:
    driver: bridge
  
volumes:
  data:
    driver_opts:
      type: none
      o: bind
      device: /home/ael-idri/data/db
  wpress:
    driver_opts:
      type: none
      o: bind
      device: /home/ael-idri/data/wp

