FROM debian:buster

RUN apt-get update && apt-get install nginx -y 

WORKDIR /var/www/html/

# RUN rm index.html

COPY index.html /var/www/html/
COPY styles.css /var/www/html/

EXPOSE 80

CMD	["nginx", "-g", "daemon off;"]
# CMD tail -f