# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ael-idri <ael-idri@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/05 11:34:00 by ael-idri          #+#    #+#              #
#    Updated: 2022/11/05 11:51:41 by ael-idri         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'
services:
  nginx:
    build: ./nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443"

    
