# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ael-idri <ael-idri@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/05 11:34:00 by ael-idri          #+#    #+#              #
#    Updated: 2022/11/05 11:51:41 by ael-idri         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
       
version: '3'

services:

  mariadb:
    build: 
        context: ./mariadb/
        args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - chabaka
    volumes:
      - data:/var/lib/mysql
    restart: always

  redis:
    build: ./bonus/redis/
    image: redis
    container_name: redis
    networks:
      - chabaka
    restart: always

  adminer:
    build: ./bonus/adminer/
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - chabaka
    restart: always

  ftp:
    build: ./bonus/ftp/
    image: ftp
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    environment:
      - FTP_USER=hliwa
      - FTP_PASS=secret
      - PASV_ADDRESS=localhost
    networks:
      - chabaka
    restart: always

  website:
    build: ./bonus/website/
    image: website
    container_name: website
    ports:
      - "80:80"
    networks:
      - chabaka
    restart: always

  wordpress:
    build:
      context: ./wordpress/
      args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
          ADMIN_USER: $ADMIN_USER
          ADMIN_PASSWORD: $ADMIN_PASSWORD
    image : wordpress
    env_file: .env
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wpress:/var/www/html/
    networks:
      - chabaka
    restart: always

  nginx:
    build:
      context: ./nginx/
      args:
        _CERTIF: $_CERTIF
        _CERTIF_key: $_CERTIF_key
        _CERTIF_crt : $_CERTIF_crt
    image: nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wpress:/var/www/html/
    networks:
      - chabaka
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always



networks:
  chabaka:
    driver: bridge
  
volumes:
  data:
  wpress:

