# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ael-idri <ael-idri@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/05 11:34:00 by ael-idri          #+#    #+#              #
#    Updated: 2022/11/05 11:51:41 by ael-idri         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
#sir 3allah
version: '3'
services:
  nginx:
    build: ./nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always 
  # mariadb:
  #   build: ./mariadb/
  #   image: mariadb
  #   container_name: mariadb
  #   # environment:
  #   #   MYSQL_DATABASE: yourdb
  #   #   MYSQL_ROOT_PASSWORD: secret
  #   #   MYSQL_USER: hliwa
  #   #   MYSQL_PASSWORD: secret
  #   networks:
  #     - app-network
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - data:/var/lib/mysql
  #   # restart: always

  # adminer:
  #   build: ./adminer/
  #   image: adminer
  #   container_name: adminer
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network
    # restart: always

# networks:
#   app-network:
#     driver: bridge
  
# volumes:
#   data:

