FROM debian:buster

RUN  apt-get update && apt-get install vsftpd vim -y
RUN cp /etc/vsftpd.conf /etc/vsftpd.conf.bak

COPY ftp-conf.sh /tmp

EXPOSE 20 21 10000-10100

ENTRYPOINT [ "/bin/bash", "/tmp/ftp-conf.sh" ]