
FROM debian:buster

ARG MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
ARG MYSQL_USER=$MYSQL_USER
ARG MYSQL_PASSWORD=$MYSQL_PASSWORD
ARG ADMIN_USER=$ADMIN_USER
ARG ADMIN_PASSWORD=$ADMIN_PASSWORD

RUN apt update && apt-get install php-fpm php-mysql vim curl -y

WORKDIR /var/www/html

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
RUN wp --allow-root core download

COPY ./wp-config.sh /tmp/

ENTRYPOINT [ "/bin/bash", "/tmp/wp-config.sh" ]
